#!/bin/bash

# Add missing translation keys for sysproxy and tun pages

# English
cat src/renderer/src/locales/en-US.json | jq '. + {
  "sysproxy.host": "Proxy Host",
  "sysproxy.host.placeholder": "Default: 127.0.0.1, do not modify unless necessary",
  "sysproxy.mode": "Proxy Mode",
  "sysproxy.mode.manual": "Manual",
  "sysproxy.mode.auto": "PAC",
  "sysproxy.uwp": "UWP Tool",
  "sysproxy.uwp.open": "Open UWP Tool",
  "sysproxy.settingMode": "Setting Mode",
  "sysproxy.settingMode.exec": "Execute Command",
  "sysproxy.settingMode.service": "Service Mode",
  "sysproxy.onlyActive": "Only for Active Interface",
  "sysproxy.onlyActive.tip": "When enabled, system proxy will only be set for currently active network interface, only works in service mode",
  "sysproxy.pac": "Proxy Mode",
  "sysproxy.pac.edit": "Edit PAC Script",
  "sysproxy.bypass.add": "Add Default Proxy Bypass",
  "sysproxy.bypass.list": "Proxy Bypass List",
  "sysproxy.bypass.placeholder": "Example: *.baidu.com",
  "tun.stack": "TCP/IP Stack",
  "tun.device": "Device Name",
  "tun.mtu": "MTU",
  "tun.strictRoute": "Strict Route",
  "tun.dnsHijack": "DNS Hijack",
  "tun.autoRoute": "Auto Route",
  "tun.autoDetect": "Auto Detect Interface",
  "tun.ipv4Address": "IPv4 Address",
  "tun.ipv6Address": "IPv6 Address",
  "tun.inet4RouteAddress": "IPv4 Route Address",
  "tun.inet6RouteAddress": "IPv6 Route Address",
  "tun.inet4RouteExcludeAddress": "IPv4 Route Exclude Address",
  "tun.inet6RouteExcludeAddress": "IPv6 Route Exclude Address",
  "tun.includeUid": "Include UID",
  "tun.includeUidRange": "Include UID Range",
  "tun.excludeUid": "Exclude UID",
  "tun.excludeUidRange": "Exclude UID Range",
  "tun.includeAndroid": "Include Android User",
  "tun.includePackage": "Include Package",
  "tun.excludePackage": "Exclude Package"
}' > /tmp/en-US.json && mv /tmp/en-US.json src/renderer/src/locales/en-US.json

# Russian  
cat src/renderer/src/locales/ru-RU.json | jq '. + {
  "sysproxy.host": "Хост прокси",
  "sysproxy.host.placeholder": "По умолчанию: 127.0.0.1, не изменяйте без необходимости",
  "sysproxy.mode": "Режим прокси",
  "sysproxy.mode.manual": "Ручной",
  "sysproxy.mode.auto": "PAC",
  "sysproxy.uwp": "Инструмент UWP",
  "sysproxy.uwp.open": "Открыть инструмент UWP",
  "sysproxy.settingMode": "Режим настройки",
  "sysproxy.settingMode.exec": "Выполнить команду",
  "sysproxy.settingMode.service": "Режим службы",
  "sysproxy.onlyActive": "Только для активного интерфейса",
  "sysproxy.onlyActive.tip": "При включении системный прокси будет установлен только для активного сетевого интерфейса, работает только в режиме службы",
  "sysproxy.pac": "Режим прокси",
  "sysproxy.pac.edit": "Редактировать скрипт PAC",
  "sysproxy.bypass.add": "Добавить обход прокси по умолчанию",
  "sysproxy.bypass.list": "Список обхода прокси",
  "sysproxy.bypass.placeholder": "Пример: *.baidu.com",
  "tun.stack": "Стек TCP/IP",
  "tun.device": "Имя устройства",
  "tun.mtu": "MTU",
  "tun.strictRoute": "Строгий маршрут",
  "tun.dnsHijack": "Перехват DNS",
  "tun.autoRoute": "Авто маршрут",
  "tun.autoDetect": "Авто определение интерфейса",
  "tun.ipv4Address": "IPv4 адрес",
  "tun.ipv6Address": "IPv6 адрес",
  "tun.inet4RouteAddress": "IPv4 адрес маршрута",
  "tun.inet6RouteAddress": "IPv6 адрес маршрута",
  "tun.inet4RouteExcludeAddress": "Исключить IPv4 адрес маршрута",
  "tun.inet6RouteExcludeAddress": "Исключить IPv6 адрес маршрута",
  "tun.includeUid": "Включить UID",
  "tun.includeUidRange": "Диапазон включённых UID",
  "tun.excludeUid": "Исключить UID",
  "tun.excludeUidRange": "Диапазон исключённых UID",
  "tun.includeAndroid": "Включить пользователя Android",
  "tun.includePackage": "Включить пакет",
  "tun.excludePackage": "Исключить пакет"
}' > /tmp/ru-RU.json && mv /tmp/ru-RU.json src/renderer/src/locales/ru-RU.json

# Persian
cat src/renderer/src/locales/fa-IR.json | jq '. + {
  "sysproxy.host": "هاست پروکسی",
  "sysproxy.host.placeholder": "پیش‌فرض: 127.0.0.1، بدون نیاز تغییر ندهید",
  "sysproxy.mode": "حالت پروکسی",
  "sysproxy.mode.manual": "دستی",
  "sysproxy.mode.auto": "PAC",
  "sysproxy.uwp": "ابزار UWP",
  "sysproxy.uwp.open": "باز کردن ابزار UWP",
  "sysproxy.settingMode": "حالت تنظیم",
  "sysproxy.settingMode.exec": "اجرای دستور",
  "sysproxy.settingMode.service": "حالت سرویس",
  "sysproxy.onlyActive": "فقط برای رابط فعال",
  "sysproxy.onlyActive.tip": "وقتی فعال است، پروکسی سیستم فقط برای رابط شبکه فعال تنظیم می‌شود، فقط در حالت سرویس کار می‌کند",
  "sysproxy.pac": "حالت پروکسی",
  "sysproxy.pac.edit": "ویرایش اسکریپت PAC",
  "sysproxy.bypass.add": "افزودن بای‌پس پروکسی پیش‌فرض",
  "sysproxy.bypass.list": "لیست بای‌پس پروکسی",
  "sysproxy.bypass.placeholder": "مثال: *.baidu.com",
  "tun.stack": "پشته TCP/IP",
  "tun.device": "نام دستگاه",
  "tun.mtu": "MTU",
  "tun.strictRoute": "مسیر سخت‌گیرانه",
  "tun.dnsHijack": "هایجک DNS",
  "tun.autoRoute": "مسیر خودکار",
  "tun.autoDetect": "تشخیص خودکار رابط",
  "tun.ipv4Address": "آدرس IPv4",
  "tun.ipv6Address": "آدرس IPv6",
  "tun.inet4RouteAddress": "آدرس مسیر IPv4",
  "tun.inet6RouteAddress": "آدرس مسیر IPv6",
  "tun.inet4RouteExcludeAddress": "حذف آدرس مسیر IPv4",
  "tun.inet6RouteExcludeAddress": "حذف آدرس مسیر IPv6",
  "tun.includeUid": "شامل UID",
  "tun.includeUidRange": "محدوده UID شامل",
  "tun.excludeUid": "حذف UID",
  "tun.excludeUidRange": "محدوده UID حذف شده",
  "tun.includeAndroid": "شامل کاربر Android",
  "tun.includePackage": "شامل بسته",
  "tun.excludePackage": "حذف بسته"
}' > /tmp/fa-IR.json && mv /tmp/fa-IR.json src/renderer/src/locales/fa-IR.json

# Chinese
cat src/renderer/src/locales/zh-CN.json | jq '. + {
  "sysproxy.host": "代理主机",
  "sysproxy.host.placeholder": "默认 127.0.0.1 若无特殊需求请勿修改",
  "sysproxy.mode": "代理模式",
  "sysproxy.mode.manual": "手动",
  "sysproxy.mode.auto": "PAC",
  "sysproxy.uwp": "UWP 工具",
  "sysproxy.uwp.open": "打开 UWP 工具",
  "sysproxy.settingMode": "设置方式",
  "sysproxy.settingMode.exec": "执行命令",
  "sysproxy.settingMode.service": "服务模式",
  "sysproxy.onlyActive": "仅为活跃接口设置",
  "sysproxy.onlyActive.tip": "开启后，系统代理仅会为当前活跃的网络接口设置，仅服务模式下生效",
  "sysproxy.pac": "代理模式",
  "sysproxy.pac.edit": "编辑 PAC 脚本",
  "sysproxy.bypass.add": "添加默认代理绕过",
  "sysproxy.bypass.list": "代理绕过列表",
  "sysproxy.bypass.placeholder": "例：*.baidu.com",
  "tun.stack": "TCP/IP 协议栈",
  "tun.device": "设备名称",
  "tun.mtu": "MTU",
  "tun.strictRoute": "严格路由",
  "tun.dnsHijack": "DNS 劫持",
  "tun.autoRoute": "自动路由",
  "tun.autoDetect": "自动检测接口",
  "tun.ipv4Address": "IPv4 地址",
  "tun.ipv6Address": "IPv6 地址",
  "tun.inet4RouteAddress": "IPv4 路由地址",
  "tun.inet6RouteAddress": "IPv6 路由地址",
  "tun.inet4RouteExcludeAddress": "IPv4 路由排除地址",
  "tun.inet6RouteExcludeAddress": "IPv6 路由排除地址",
  "tun.includeUid": "包含 UID",
  "tun.includeUidRange": "包含 UID 范围",
  "tun.excludeUid": "排除 UID",
  "tun.excludeUidRange": "排除 UID 范围",
  "tun.includeAndroid": "包含 Android 用户",
  "tun.includePackage": "包含应用包名",
  "tun.excludePackage": "排除应用包名"
}' > /tmp/zh-CN.json && mv /tmp/zh-CN.json src/renderer/src/locales/zh-CN.json

echo "Sysproxy and TUN translation keys added!"
